# Generated by Django 6.1.2 on 2026-10-09 05:25

import django.db.models.deletion
import django.utils.timezone
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


import json
import uuid


def convert_body_to_json(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT page_ptr_id, body FROM blog_blogpage")
        rows = cursor.fetchall()
        for page_id, raw_body in rows:
            if raw_body and not (str(raw_body).startswith("[") or str(raw_body).startswith("{")):
                # Convert raw HTML into wagtail rich text stream block
                block_id = str(uuid.uuid4())
                stream_json = json.dumps([{"type": "paragraph", "value": raw_body, "id": block_id}])
                cursor.execute(
                    "UPDATE blog_blogpage SET body = %s WHERE page_ptr_id = %s",
                    [stream_json, page_id],
                )


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpage'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtaildocs', '0014_alter_document_file_size'),
        ('wagtailimages', '0027_image_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(convert_body_to_json, migrations.RunPython.noop),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(help_text='URL slug for category filtering', max_length=80, unique=True)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('icon', models.CharField(default='code', help_text='Icon identifier e.g. python, cpu, server, bot, database, cloud, terminal', max_length=50)),
                ('color', models.CharField(default='#4f46e5', help_text='Hex color code for badge styling (e.g. #4f46e5, #059669, #0284c7)', max_length=20)),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='posts_per_page',
            field=models.PositiveIntegerField(default=6, help_text='Number of articles to display per page'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='author_name',
            field=models.CharField(blank=True, help_text='Custom display author name if different from account username', max_length=100),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='header_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='manual_read_time',
            field=models.PositiveIntegerField(blank=True, help_text='Optional reading time in minutes (calculated automatically if left blank)', null=True),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('code', 5), ('callout', 9), ('quote', 13), ('image', 17), ('document', 21), ('embed', 22)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'help_text': 'Section sub-heading', 'icon': 'title', 'label': 'Heading'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h3', 'h4', 'bold', 'italic', 'link', 'ol', 'ul', 'hr', 'code', 'blockquote'], 'icon': 'pilcrow'}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'File name or code title (e.g. models.py, main.go)', 'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('python', 'Python'), ('javascript', 'JavaScript'), ('typescript', 'TypeScript'), ('html', 'HTML'), ('css', 'CSS'), ('sql', 'SQL'), ('bash', 'Bash / Shell'), ('json', 'JSON'), ('yaml', 'YAML'), ('dockerfile', 'Dockerfile'), ('rust', 'Rust'), ('go', 'Go'), ('csharp', 'C#'), ('cpp', 'C++'), ('plaintext', 'Plain Text')]}), 4: ('wagtail.blocks.TextBlock', (), {'help_text': 'Paste your code here'}), 5: ('wagtail.blocks.StructBlock', [[('title', 2), ('language', 3), ('code', 4)]], {}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Info (Blue)'), ('tip', 'Pro Tip (Green)'), ('warning', 'Warning (Amber)'), ('important', 'Important (Purple)')]}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional title for the callout box', 'required': False}), 8: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'code', 'ul', 'ol']}), 9: ('wagtail.blocks.StructBlock', [[('callout_type', 6), ('title', 7), ('text', 8)]], {}), 10: ('wagtail.blocks.TextBlock', (), {}), 11: ('wagtail.blocks.CharBlock', (), {'help_text': 'Author or source', 'required': False}), 12: ('wagtail.blocks.CharBlock', (), {'help_text': 'Source title / book / talk', 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('quote', 10), ('author', 11), ('source_title', 12)]], {}), 14: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 15: ('wagtail.blocks.CharBlock', (), {'help_text': 'Image caption', 'required': False}), 16: ('wagtail.blocks.CharBlock', (), {'help_text': 'Alt text for accessibility', 'required': False}), 17: ('wagtail.blocks.StructBlock', [[('image', 14), ('caption', 15), ('alt_text', 16)]], {}), 18: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 19: ('wagtail.blocks.CharBlock', (), {'help_text': 'Custom display title for the file', 'required': False}), 20: ('wagtail.blocks.CharBlock', (), {'help_text': 'Short description of this file', 'required': False}), 21: ('wagtail.blocks.StructBlock', [[('document', 18), ('title', 19), ('description', 20)]], {}), 22: ('wagtail.embeds.blocks.EmbedBlock', (), {'icon': 'media', 'label': 'Embed (YouTube, Vimeo, etc.)'})}),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Post date'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='intro',
            field=models.CharField(help_text='Summary/excerpt shown on cards and search results', max_length=350),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='blog.blogcategory'),
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('author_email', models.EmailField(blank=True, max_length=254)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=True, help_text='Approved comments are visible to all readers')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blogpage')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blog Comment',
                'verbose_name_plural': 'Blog Comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogPageDocumentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(blank=True, help_text='Custom title for this document (e.g. Source Code Archive, PDF Cheat Sheet)', max_length=255)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtaildocs.document')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='blog.blogpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlogPageGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=250)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='blog.blogpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlogPageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='blog.blogpage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='blogpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='blog.BlogPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
