# Generated by Django 6.1.2 on 2026-10-09 05:45

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogcategory_blogindexpage_posts_per_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='reader_comments', to='blog.blogpage'),
        ),
    ]
