# Generated by Django 6.1.2 on 2026-10-09 05:25

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_snippet',
            field=wagtail.fields.RichTextField(blank=True, help_text='Optional brief author/site intro on the homepage'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_badge',
            field=models.CharField(default='Engineering & Technology', help_text='Small badge above main hero heading', max_length=60),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.CharField(default='In-depth technical guides, engineering thoughts, and hands-on explorations across Python, Backend Architecture, Artificial Intelligence, and Modern Cloud Systems.', help_text='Hero description', max_length=350),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(default='Exploring Modern Technology, Systems & AI', help_text='Main hero heading', max_length=150),
        ),
    ]
